#!/bin/bash

function getLanguage(){
  language=$(
    yad --borders=32 --text="<big><b>Escolha o idioma do sistema</b></big>\n" --list --fixed                 \
        --center --no-headers --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"   \
        "Português Brasileiro"                                                                    \
        "Português Europeu"                                                                       \
        "English"                                                                                 \
        "Español" || exit 0
  )
}
 
function getKeyboard(){
layouts=$(grep -A9999 '! layout' /usr/share/X11/xkb/rules/evdev.lst | sed -n 2,9999p)
layouts=$(echo "${layouts}" | sed -n 1,$(echo "${layouts}" | grep -m1 -n '!' | cut -d: -f1)p \
                            | grep -Ev '!|^$|custom' \
                            | sed 's|Portuguese|Português|g;s|Spanish|Español|g;s| (|§(|g'\
                            | sed ':l s/\(([^ )]*\)[ ]/\1§/;tl'\
                            | sed 's|§| |g' | awk '{print $2,$1}' | sort)

variations=$(grep -A9999 '! variant' /usr/share/X11/xkb/rules/evdev.lst | sed -n 2,9999p)
variations=$(echo "${variations}" | sed -n 1,$(echo "${variations}" | grep -m1 -n '!' | cut -d: -f1)p \
                                  | grep -Ev '!|^$|custom' \
                                  | sed ':l s/\(([^ )]*\)[ ]/\1§/;tl' | sed 's| (|§(|g'\
                                  | sed 's|§| |g' | grep "${keyboard_layout}": | awk '{print $1,$3}' | sort)

keyboard_layout=$(
    yad --borders=32 --text="<big><b>Escolha O idioma do seu teclado</b></big>\n" --list  \
        --fixed --hide-column=2 --center --no-headers --column= --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"         \
        ${layouts} | cut -d'|' -f2 || exit 0
  )

keyboard_variation=$(
    yad --borders=32 --text="<big><b>Escolha O idioma do seu teclado</b></big>\n" --list  \
        --fixed --center --no-headers --column= --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"         \
        br "Tradicional" \
        ${variations} | cut -d'|' -f2 || { getKeyboard; return; }
  )

keyboard_layout=${keyboard_layout}_${keyboard_variation}

  echo "TODO"
}
 
function getAccountDetails(){
  erro_validacao="${1}"; shift
  
  [ "${erro_validacao}" = "" ] && {
    erro_validacao="Essa senha será utilizada para instalar programas"
  }
  
  account=$(
    yad --borders=32 --text="<big><b>Criar o usuário administrador</b></big>\n<small>${erro_validacao} </small>\n"  --form --fixed  \
        --center --width=640 --height=480  --title="Tiger OS - Instalar sistema"                 \
        --field="\nNome da empresa     \n"                                     \
        --field=" ":lbl --field="Nome de usuário  "                             \
        --field=" ":lbl --field="Senha de acesso":H                                    \
        --field="Confirme a senha":H                                          \
        --field=" ":lbl "${@}" || exit 0
  )
  
  user_fullname=$(echo ${account} | cut -d\| -f1)
  user_name=$(echo ${account}     | cut -d\| -f3)
  
  user_password=$(echo ${account} | cut -d\| -f5)
  test_password=$(echo ${account} | cut -d\| -f6)
  
  [ "${user_name}" = "root" ] && {
    getAccountDetails '<b>Erro:</b> root é um nome reservado' "${user_fullname}" "" "" "" "${user_password}" "${test_password}"
  }
  
  [ "${user_name}" = "" ] && {
    getAccountDetails '<b>Erro:</b> Faltou o nome de usuário' "${user_fullname}" "" "${user_name}" "" "${user_password}" "${test_password}"
  }
  
  user_name_valid=$(echo "${user_name}" | iconv -t ASCII//TRANSLIT | tr '[:upper:]' '[:lower:]' \
                                        | tr ' ' '_' | sed 's|[^a-zA-Z0-9_-]||g;s|^-|_|g')
                                        
  [ ! "${user_name}" = "${user_name_valid}" ] && {
    yad --borders=32 --text="<big><b>Nome '${user_name}' não é válido como nome de usuário</b>\n\n O instalador sugere <b>${user_name_valid}</b>, deseja utilizar?</big>\n" --list --fixed             \
        --center --width=640 --title="Tiger OS - Instalar sistema" --button=gtk-no:1 --button=gtk-ok:0 \
        || {
          getAccountDetails '<b>Erro:</b> Nome de usuário inválido' "${user_fullname}" "" "${user_name_valid}" "" "${user_password}" "${test_password}"
          return
        }
    
    user_name="${user_name_valid}"
  }
  
  [ "${user_password}" = "" ] && {
    getAccountDetails '<b>Erro:</b> Faltou a senha' "${user_fullname}" "" "${user_name}" "" "" ""
  }
  
  [ ! "${user_password}" = "${test_password}" ] && {
    getAccountDetails "<b>Erro:</b> Senhas não conferem" "${user_fullname}" "" "${user_name}" 
    return
  }
  
}

function getTimezone(){
  area=$(
    yad --borders=32 --text="<big><b>Escolha a região do fuso-horário</b></big>\nHorário padrão de Brasília: América/São paulo\n" --list  \
        --fixed --hide-column=1 --center --no-headers --column= --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"         \
        $(timedatectl list-timezones | awk '{print $0 " " strftime("%z", systime())}'                                                     \
            | grep / | cut -d/ -f1 | sort | uniq        \
            | sed "s|Africa|África|g"                   \
            | sed "s|America|América|g"                 \
            | sed "s|Antarctica|Horário da Antártica|g" \
            | sed "s|Atlantic|Horário do Atlânco|g"     \
            | sed "s|Arctic|Horário do Ártico|g"        \
            | sed "s|Asia|Ásia|g"                       \
            | sed "s|Australia|Áustrália|g"             \
            | sed "s|Canada|Canadá|g"                   \
            | sed "s|Chile|Chile|g"                     \
            | sed "s|Etc|GMT|g"                         \
            | sed "s|Indian|Índia|g"                    \
            | sed "s|Mexico|México|g"                   \
            | sed "s|Pacific|Horário do Pacífico|g"     \
            | sed "s|US|EUA|g"                          \
            | sed "s|Brazil|Brasil|g"                   \
            | cat -n) || exit 0
  )
  
  area=$(
    timedatectl list-timezones | awk '{print $0 " " strftime("%z", systime())}' | grep / | cut -d/ -f1  \
                               | sort | uniq | cat -n |  sed 's|^ *||g'                                 \
                               | grep "^$(echo "${area}"                                                \
                               | cut -d'|' -f1)"                                                        \
                               | sed 's|^[0-9].*[[:space:]]||g'
  )
  
  city=$(
    yad --borders=32 --text="<big><b>Escolha a região do fuso-horário</b></big>\nHorário padrão de Brasília: América/São paulo\n" --list  \
        --fixed --hide-column=1 --center --no-headers --column= --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"         \
        $(timedatectl list-timezones | sort | uniq  | grep ${area}              \
                                     | cut -d'/' -f2-99                         \
                                     | sed 's|St_|St. |g;s|_| |g;s|Sao |São |g' \
                                     | cat -n )|| { getTimezone; return; }
  )
  
  area=$(timedatectl list-timezones | sort | uniq  | grep ${area} | sed -n $(echo ${city} |cut -d\| -f1)p)
    
}

function getInstallMethod() {
  method=$(
    yad --borders=32 --text="<big><b>Escolha o método de instalação</b></big>\n" --list --fixed           \
        --center --no-headers --column= --width=640 --height=480 --title="Tiger OS - Instalar sistema"           \
        "Usar o disco inteiro"                                                                            \
        "Usar uma partição"                                                                               \
        "Avançado"  || exit 0
  )
  
  [ "${method}" = "Avançado|" ] && {
     gparted
  }
  
  getDisk
}
 
function getDisk(){
  disk=$(
    yad --borders=32 --text="<big><b>Escolha onde o Tiger 23 será instalado</b></big>\n" --list --fixed             \
        --center --width=640 --height=480 --title="Tiger OS - Instalar sistema"                                            \
        --column="Dispositivo             " --column="Tamanho"                                                      \
        $(lsblk -a -o NAME,SIZE,TYPE | grep disk | sed 's|disk||g;s|^|/dev/|g' | grep -Ev "ram|M")  | cut -d\| -f1  \
        || { getInstallMethod; return; }
  )
  
  [ "${method}" = "Usar uma partição|" ] && {
     getPartition
  }
  
  [ "${method}" = "Avançado|" ] && {
     getPartition
  }
}

function getPartition(){
  partitions_list=$(lsblk -a -o NAME,SIZE,TYPE | grep part | sed 's| part||g;s|[├─└]||g;s|^|/dev/|g')
  
  [ "${partitions_list}" = "" ] && {
    yad --borders=32 --text="<big><b>O Disco ${disk} não possui partições</b>\nSelecione \"Usar o disco inteiro\" ou crie as partições no modo \"Avançado\" antes</big>\n" --list --fixed             \
        --center --width=640 --title="Tiger OS - Instalar sistema"
        
    getInstallMethod
    return
  }

  sys_part=$(
    yad --borders=32 --text="<big><b>Escolha a partição onde o Tiger 23 será instalado</b></big>\n" --list --fixed  \
        --center --width=640 --height=480 --title="Tiger OS - Instalar sistema"                                            \
        --column="Dispositivo             " --column="Tamanho"                                                      \
        $(lsblk -a -o NAME,SIZE,TYPE | grep part | sed 's| part||g;s|[├─└]||g;s|^|/dev/|g') | grep "${disk}" | cut -d\| -f1  \
        || || { getDisk; return; }
  )
}

function getInstallMethod(){
  echo "TODO"
}
 
getLanguage
getKeyboard
getAccountDetails
getTimezone
getInstallMethod
doInstallation
